name: 'clickup-change-task-assignee'
description: 'Github action to automatically change the status of task in Clickup'
author: 'Tjitse-E'
runs:
    using: 'node12'
    main: 'dist/index.js'
inputs:
    clickup_token:
        description: Your clickup token
        required: true
    clickup_custom_task_ids:
        description: A list of custom task IDS of which you want to change the status
        required: true
    clickup_team_id:
        description: Your clickup team id
        required: true
    target_assignees_usernames:
        description: The Github usernames of the target assignees
        required: true
    clickup_user_id_mapping_path:
        description: Expects a JSON file path that maps the Github users to Clickup user id's
        required: true

